### ISSUE TITLE
Meta Spark Tests

### ISSUE THREAD

**Issue by ConanMG** [ConanMG/ConanMG#2]

**Comment by ConanMG** [comment]
- [x] Display something AR on a QR code.
- [ ] Play sounds on contact with QR code.
- [ ] Display something AR on a bottle label.
